

services:
  db:
    image: postgres:latest
    container_name: phonebook_db
    restart: always
    environment:
      POSTGRES_DB: phonebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lego
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: ./app
    container_name: phonebook_app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: phonebook
      DB_USER: postgres
      DB_PASSWORD: lego
    command: ["python", "back.py"]

volumes:
  pg_data:
